name: ci node
on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    checkout-job:
        runs-on: ubuntu-slim
        #deafult to nodejs directory to avoid repetitive declaration
        defaults:
          run:
            working-directory: ./nodejs

        steps:
          - name: code checkout
            uses: actions/checkout@v4
        
          - name: build node
            uses: actions/setup-node@v4
            with:
                node-version: 22
                cache: 'npm'
                # cache-dependency-path: './nodejs/package-lock.json'

          - name: cache dependencies
            id: react-cache
            uses: actions/cache@v6
            with:
              path: ~/.npm            
              key: ${{ runner.os }}-artifact-${{ hashFiles('**/package-lock.json') }}
              restore-keys: |
                ${{ runner.os }}-aritifact-

          - name: install deps
            # if: steps.react-cache.outputs.cache-hit != 'true'
            # working-directory: ./nodejs
            run: npm ci

          - name: node lint
            # working-directory: ./nodejs
            run: npm run lint
            
          - name: run test cases
            # working-directory: ./nodejs
            run: echo "performed tets cases"

          - name: build react app
            # working-directory: ./nodejs
            run: npm run build

          - name: upload artifact
            uses: actions/upload-artifact@v7
            with:
              name: node-artifact
              path: ./nodejs/build/
              #retention-days: 5