name: rollback deploy(on failure)

on: 
    push:
        branches:
            - qa
jobs:
    deploy-job:
        runs-on: "ubuntu-slim"
        steps:
            - name: deploying app
              run: echo "deploying.." && false
            - name: rollback deployment
              if: failure()
              run: echo "rollback is successfull"